kind: Service
apiVersion: v1
metadata:
  name: will42-service
  namespace: dev
spec:
  selector:
    app: will42
  ports:
    - protocol: TCP
      port: 88
      targetPort: 8888
  type: LoadBalancer