kind: Service
apiVersion: v1
metadata:
  name: will42-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: will42
  ports:
    - protocol: TCP
      port: 88
      targetPort: 8888
      nodePort: 8888